// <auto-generated />
using System;
using MainLedger.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MainLedger.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MailLedgerDbContext))]
    [Migration("20260107201756_AddExtractionCandidates")]
    partial class AddExtractionCandidates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MainLedger.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<string>("Changes")
                        .HasColumnType("jsonb")
                        .HasColumnName("changes");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("EntityId")
                        .HasDatabaseName("ix_audit_logs_entity_id");

                    b.HasIndex("EntityType")
                        .HasDatabaseName("ix_audit_logs_entity_type");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_audit_logs_timestamp");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_audit_logs_user_id");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_logs_entity_type_id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("MainLedger.Domain.Entities.EmailMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BodyText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body_text");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<double?>("ClassificationConfidence")
                        .HasColumnType("double precision")
                        .HasColumnName("classification_confidence");

                    b.Property<DateTime?>("ClassifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("classified_at");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Directive")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("directive");

                    b.Property<string>("DirectiveReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("directive_reason");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("from");

                    b.Property<bool?>("IsFinancial")
                        .HasColumnType("boolean")
                        .HasColumnName("is_financial");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_processed");

                    b.Property<Guid?>("MatchedRuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("matched_rule_id");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("message_id");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("subject");

                    b.Property<string>("ThreadId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("thread_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_email_messages_category");

                    b.HasIndex("ContentHash")
                        .IsUnique()
                        .HasDatabaseName("ix_email_messages_content_hash");

                    b.HasIndex("Directive")
                        .HasDatabaseName("ix_email_messages_directive");

                    b.HasIndex("IsFinancial")
                        .HasDatabaseName("ix_email_messages_is_financial");

                    b.HasIndex("IsProcessed")
                        .HasDatabaseName("ix_email_messages_is_processed");

                    b.HasIndex("MessageId")
                        .HasDatabaseName("ix_email_messages_message_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_email_messages_user_id");

                    b.ToTable("email_messages", (string)null);
                });

            modelBuilder.Entity("MainLedger.Domain.Entities.ExtractionCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double?>("AmountConfidence")
                        .HasColumnType("double precision")
                        .HasColumnName("amount_confidence");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<double?>("DateConfidence")
                        .HasColumnType("double precision")
                        .HasColumnName("date_confidence");

                    b.Property<Guid>("EmailMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("email_message_id");

                    b.Property<Guid>("ExtractionVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("extraction_version_id");

                    b.Property<string>("Merchant")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("merchant");

                    b.Property<double?>("MerchantConfidence")
                        .HasColumnType("double precision")
                        .HasColumnName("merchant_confidence");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reference_id");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("SourceAccount")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_account");

                    b.Property<string>("SourceBank")
                        .HasColumnType("jsonb")
                        .HasColumnName("source_bank");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TargetAccount")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("target_account");

                    b.Property<string>("TargetBank")
                        .HasColumnType("jsonb")
                        .HasColumnName("target_bank");

                    b.Property<DateTime?>("TransactionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("transaction_date");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_extraction_candidates_created_at");

                    b.HasIndex("EmailMessageId")
                        .HasDatabaseName("ix_extraction_candidates_email_message_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_extraction_candidates_status");

                    b.ToTable("extraction_candidates", (string)null);
                });

            modelBuilder.Entity("MainLedger.Domain.Entities.ExtractionVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeprecatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deprecated_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model_name");

                    b.Property<string>("PromptHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("prompt_hash");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_extraction_versions_is_active");

                    b.HasIndex("Version")
                        .IsUnique()
                        .HasDatabaseName("ix_extraction_versions_version");

                    b.ToTable("extraction_versions", (string)null);
                });

            modelBuilder.Entity("MainLedger.Domain.Entities.FinancialRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("direction");

                    b.Property<Guid>("EmailMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("email_message_id");

                    b.Property<string>("ExtractionVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("extraction_version");

                    b.Property<string>("Merchant")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("merchant");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rejected_at");

                    b.Property<string>("SourceAccount")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source_account");

                    b.Property<string>("SourceBank")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("source_bank");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("TargetAccount")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("target_account");

                    b.Property<string>("TargetBank")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("target_bank");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("transaction_date");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("EmailMessageId")
                        .IsUnique()
                        .HasDatabaseName("ix_financial_records_email_message_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_financial_records_status");

                    b.HasIndex("TransactionDate")
                        .HasDatabaseName("ix_financial_records_transaction_date");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_financial_records_user_id");

                    b.HasIndex("UserId", "Status", "TransactionDate")
                        .HasDatabaseName("ix_financial_records_user_status_date");

                    b.ToTable("financial_records", (string)null);
                });

            modelBuilder.Entity("MainLedger.Domain.Entities.GmailConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("HistoryId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("history_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("refresh_token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_gmail_connections_is_active");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_gmail_connections_user_id");

                    b.ToTable("gmail_connections", (string)null);
                });

            modelBuilder.Entity("MainLedger.Domain.Entities.Rule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("KeywordPattern")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("keyword_pattern");

                    b.Property<string>("LabelPattern")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("label_pattern");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("SenderPattern")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("sender_pattern");

                    b.Property<string>("SubjectPattern")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("subject_pattern");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_rules_is_active");

                    b.HasIndex("Priority")
                        .HasDatabaseName("ix_rules_priority");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_rules_user_id");

                    b.ToTable("rules", (string)null);
                });

            modelBuilder.Entity("MainLedger.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_users_is_active");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MainLedger.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("MainLedger.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MainLedger.Domain.Entities.EmailMessage", b =>
                {
                    b.HasOne("MainLedger.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MainLedger.Domain.Entities.ExtractionCandidate", b =>
                {
                    b.OwnsOne("MainLedger.Domain.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("ExtractionCandidateId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");

                            b1.HasKey("ExtractionCandidateId");

                            b1.ToTable("extraction_candidates");

                            b1.WithOwner()
                                .HasForeignKey("ExtractionCandidateId");
                        });

                    b.OwnsOne("MainLedger.Domain.ValueObjects.Money", "Fees", b1 =>
                        {
                            b1.Property<Guid>("ExtractionCandidateId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("fees_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("fees_currency");

                            b1.HasKey("ExtractionCandidateId");

                            b1.ToTable("extraction_candidates");

                            b1.WithOwner()
                                .HasForeignKey("ExtractionCandidateId");
                        });

                    b.OwnsOne("MainLedger.Domain.ValueObjects.Money", "Tax", b1 =>
                        {
                            b1.Property<Guid>("ExtractionCandidateId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("tax_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("tax_currency");

                            b1.HasKey("ExtractionCandidateId");

                            b1.ToTable("extraction_candidates");

                            b1.WithOwner()
                                .HasForeignKey("ExtractionCandidateId");
                        });

                    b.Navigation("Amount");

                    b.Navigation("Fees");

                    b.Navigation("Tax");
                });

            modelBuilder.Entity("MainLedger.Domain.Entities.FinancialRecord", b =>
                {
                    b.HasOne("MainLedger.Domain.Entities.EmailMessage", null)
                        .WithMany()
                        .HasForeignKey("EmailMessageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MainLedger.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("MainLedger.Domain.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("FinancialRecordId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("currency");

                            b1.HasKey("FinancialRecordId");

                            b1.ToTable("financial_records");

                            b1.WithOwner()
                                .HasForeignKey("FinancialRecordId");
                        });

                    b.OwnsOne("MainLedger.Domain.ValueObjects.Money", "FeeAmount", b1 =>
                        {
                            b1.Property<Guid>("FinancialRecordId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("fee_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("fee_currency");

                            b1.HasKey("FinancialRecordId");

                            b1.ToTable("financial_records");

                            b1.WithOwner()
                                .HasForeignKey("FinancialRecordId");
                        });

                    b.OwnsOne("MainLedger.Domain.ValueObjects.Money", "TaxAmount", b1 =>
                        {
                            b1.Property<Guid>("FinancialRecordId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("tax_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("tax_currency");

                            b1.HasKey("FinancialRecordId");

                            b1.ToTable("financial_records");

                            b1.WithOwner()
                                .HasForeignKey("FinancialRecordId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("FeeAmount");

                    b.Navigation("TaxAmount");
                });

            modelBuilder.Entity("MainLedger.Domain.Entities.GmailConnection", b =>
                {
                    b.HasOne("MainLedger.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MainLedger.Domain.Entities.Rule", b =>
                {
                    b.HasOne("MainLedger.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
